### ISSUE TITLE
Dotnet-core-uninstall is another useless Microsoft tool!

### ISSUE THREAD

**Issue by Joebeazelman** [dotnet/cli-lab#102]
If I sound harsh, it's because I am sick and tired of Microsoft releasing half-baked products that don't work as expected. Microsoft products are phenomenally bad and it's a wonder how you guys still stay in business. I would feel sorry for you guys like I would for the slow kid who klutzes around the basketball court, but this isn't your first time on the court with years of effort and tons of resources. I suspect your whiteboarding hiring technique is ineffective and counterproductive.

Now to the issue at hand.  When I try to uninstall unused dotnet core SDKs and Runtimes from my server through Add/Remove Programs, I get an error "Windows cannot find "c:\ProgramData\Package Cache\{blah blha}\dotnet-runtime-2.2.7-win-x86.exe" Make sure you typed the name correctly, and then try again." I've been trying to rebuild the cache using various tools, but they only work with using **InstallerFiles** directory. Why did you guys move the cheese? What's so special about installing .NET Core that it requires a different installation strategy?  I guess it's another poor decision built upon a legacy of other equally poor decisions, i.e. a vortex or blackhole of bad decision.

I tried to use your core-uninstall-tool but it was a complete failure.  Running the command with no arguments gave me an error "Required command was not provided".  Running it with the list command gave me another error "The specified version is not valid: ""."  WTF?  If I sound hostile, it because I am kindly sharing the user hostility you're unleashing on developers trying to get work done.

Anyway, I figured I would try a hack. I downloaded the runtime again performed a repair.  It appeared to succeed, but when I tried to uninstall it from program and files, it complained that it couldn't find the package cache.  I reran the installer and selected uninstall and it mysteriously worked. Have you ever considered requiring hacks like these to get your horrible products to work only encourages hacking?  This is similar to your onerous, poorly conceived user authentication system in Windows, requiring IT personnel and end-users to just turn it off so they can get work done?

GET YOUR ACT TOGETHER MICROSOFT!!!!  Apple rose from the brink of bankruptcy and leapfrogged you guys because they cared about quality, simplicity and taste. It's why your own developers are using MacBook Pros for development.  Where's the shame?

**Comment by KathleenDollard** [comment]
This is being closed because the tone is not acceptable in our repos and is not actionable. 

Please give us steps to reproduce and otherwise help us to solve problems you identify. Telling us you are frustrated is fine, ranting is not. 

The only issue we extracted from this seems to be the same as #103.
