### ISSUE TITLE
List: specified version not valid error

### ISSUE THREAD

**Issue by sfoslund** [dotnet/cli-lab#103]
From manual testers: On Windows

List will return error -The specified version is not valid: ""  
- If installed 3.0.0 or 3.1.0 ASP.Net Core Runtime separately. 
- If installed 3.0.0-rc1 or 3.1.0-preview x .Net Core Runtime separately 

Notes:
- There is no ASP.Net Core Runtime installer for Mac, so this issue is not occurred on Mac. 
- If installed 3.0.0-rc1 or 3.1.0-preview x .Net Core Runtime separately for Mac, it is not repro on Mac. 

![GetImage](https://user-images.githubusercontent.com/16010855/71839587-5cd2a300-3070-11ea-8b65-97e258f7f116.png)

**Comment by olmelabs** [comment]
I am having the same issue  with latest release of the tool.
I must admit i have really old  sdks on my machine which i try to remove

```
PS C:\Users\Oleg> dotnet-core-uninstall list
The specified version is not valid: "".
PS C:\Users\Oleg> dotnet-core-uninstall --version
1.3.245803+acb8777eb1e90d7f0cd7dd4b881ef9b595f643db
```


![image](https://user-images.githubusercontent.com/32703675/136658421-8bad01d2-8e90-466b-9dbf-227c9b021032.png)
