### ISSUE TITLE
ASP.NET Core Runtimes could not be displayed

### ISSUE THREAD

**Issue by sfoslund** [dotnet/cli-lab#106]
From manual testers: On Windows

The ASP.NET Core Runtimes info could not be displayed 
- If Installed ASP.NET Core Runtime 3.0.0-preview7/8/9/rc1 
- If Installed ASP.NET Core Runtime 3.1.0-preview1/2/3 
Note: This issue is not repro with ASP.Net Core Runtime 3.0.0-preview1/2/3/4/5/6 

![GetImage (3)](https://user-images.githubusercontent.com/16010855/71840054-6dcfe400-3071-11ea-8de7-058832ec6720.png)

**Comment by yuki233** [comment]
The ASP.Net Core Runtime installers could be download using below URL
https://dotnet.microsoft.com/download/dotnet-core/3.0
https://dotnet.microsoft.com/download/dotnet-core/3.1

**Comment by sfoslund** [comment]
Fixed by #111
