### ISSUE TITLE
MSI improvement

### ISSUE THREAD

**Issue by wli3** [dotnet/cli-lab#117]
1. The CoreHost component uses the same component GUID for both x64 and x86. We should change that to just be Guid=”*” and have WiX generate a stable GUID. That component only sets the environment variable.

2. Change the -ag to -gg in the powershell script

3. Add `<UIRef Id="WixUI_Minimal"/>` inside the Product element for minimal UI.

**Comment by wli3** [comment]
@sfoslund if you have cycle, you can try to add it here https://github.com/dotnet/cli-lab/blob/master/src/redist/targets/packaging/windows/dotnetCoreUninstall/dotnet.wxs#L6

And make a build, see if the UI is good enough. If so, we can just 1.0 now

**Comment by wli3** [comment]
This doc site may help.
https://wixtoolset.org//documentation/manual/v3/wixui/wixui_dialog_library.html

**Comment by sfoslund** [comment]
Assigning myself since I have the work essentially finished. I'll make a PR once we decide on icons/ images in the UI.

**Comment by sfoslund** [comment]
Fixed by #120
