### ISSUE TITLE
Hitting enter does not choose default [Y/n] option

### ISSUE THREAD

**Issue by phillijw** [dotnet/cli-lab#119]
Typically the capital Y implies that it's default and you can just hit "enter" to choose it. Instead, the program requires you to actually type "y" before hitting enter.

**Comment by sfoslund** [comment]
Thanks for reaching out! As this tool can be destructive we want to be sure to get user confirmation before uninstalling. Are there situations in which requiring the `y` response causes problems for you? 

Also, note that you can use the `-y` option to avoid user input altogether (see our documentation [here](https://docs.microsoft.com/en-us/dotnet/core/additional-tools/uninstall-tool?tabs=windows#options-2)). 

cc @KathleenDollard

**Comment by phillijw** [comment]
If the `y` is required to type instead of just hitting enter, that's fine, but you should lowercase the `y` in the `[Y/n]` display text so it's not implied that it's default. I would use `[y/n]` instead so no assumptions are made by a user.

https://askubuntu.com/questions/322600/do-you-want-to-continuey-n-why-the-upper-case

**Comment by SemiNormal** [comment]
Shouldn't it be [y/N] in that case?

**Comment by phillijw** [comment]
If the user has to type something in, then there isn't a default

- If you have to type something, use `[y/n]`
- If you can hit enter and default to Yes, then `[Y/n]`
- If you can hit enter and default to No, then `[y/N]`
