### ISSUE TITLE
Where is the link to the msi file I should download!?

### ISSUE THREAD

**Issue by mowali** [dotnet/cli-lab#121]
the how to starts by saying download the msi... where is that download link?

**Comment by sfoslund** [comment]
The MSI is an asset associated with the release. See the [releases page](https://github.com/dotnet/cli-lab/releases) and click on the MSI asset to download. 

![Screenshot (23)_LI](https://user-images.githubusercontent.com/16010855/75696595-aef30780-5c60-11ea-91ac-e69a4e7f6bf9.jpg)
