### ISSUE TITLE
Add 'dotnet-core-uninstall' as .NET Core global tool

### ISSUE THREAD

**Issue by kapsiR** [dotnet/cli-lab#128]
It would be cool, if we can install the uninstaller as .NET tool:  
`dotnet tool install dotnet-core-uninstall --global`

**Comment by sfoslund** [comment]
Thanks for your feedback! This was discussed but ultimately we decided against it- please see [the note in our README](https://github.com/dotnet/cli-lab#why-isnt-the-net-core-uninstall-tool-a-net-core-global-tool) about why it didn't work out.

**Comment by kapsiR** [comment]
Thanks for clarification and for the fast response! 👍
