### ISSUE TITLE
Command location is not added to the PATH environment variable.

### ISSUE THREAD

**Issue by bjorg** [dotnet/cli-lab#132]
Is there something additional I need to be able to invoke it? After running the MSI and opening a new shell, it doesn't find the `dotnet-core-uninstall` command.

**Comment by sfoslund** [comment]
No, there shouldn't be any further steps. Which shell are you using? Have you run a repair through the MSI?

**Comment by bjorg** [comment]
It tried it from the `cmd.exe` shell in _Windows Terminal_. And yes, I did try the repair step as well without success.

**Comment by BrianTJackett** [comment]
I had the same issue when attempting to run from Windows Terminal with PowerShell 7.  I closed Windows Terminal completely and re-launched which fixed the issue.

**Comment by bjorg** [comment]
I thought I did that too, but maybe there was an open one lurking on one of my virtual desktops. I'll give it another try and report.

**Comment by bjorg** [comment]
[PEBKAC](https://www.urbandictionary.com/define.php?term=pebkac)
