### ISSUE TITLE
Installation instructions should say the MSI must be run elevated

### ISSUE THREAD

**Issue by DavidWBrooks** [dotnet/cli-lab#133]
On a normal consumer-y Win10 system, double-clicking the MSI doesn't work. I had to run it from an elevated command prompt. Can you update the install instructions?

**Comment by sfoslund** [comment]
@DavidWBrooks thanks for filing an issue, can you give me a little more information on the steps you're taking? The expected workflow for this tool is:

1. Install the tool using the MSI.
a. Download the MSI from our [releases page](https://github.com/dotnet/cli-lab/releases)
b. Double click the downloaded MSI to run
c. Click through the MSI dialog to complete install
d. The installation will finish and the MSI dialog will close. Note that we haven't run the tool yet, but it is now on the PATH for use from a shell
2. Run the tool.
a. Open an elevated command prompt
b. Run `dotnet-core-uninstall {options}` to use the tool

Are these the steps you're following? Where does it seem to be going wrong?

**Comment by DavidWBrooks** [comment]
OK, this was strange. I'm logged in as a user with admin privileges (not restricted). I download-and-ran, and then because nothing seemed to happen I double-clicked the MSI in my downloads directory (step 2). There was a brief flash of the initial MSI dialog, and then nothing. I tried it several times, and then running from an elevated CMD worked.

Past tense because I have restarted the PC for a different reason (not an update btw) and now it works as advertised. Perhaps there was a conflict deep in MSI-world; I may have accidentally started two installs at the same time. If you don't need any more from me, please close this as no-repro, and thanks for getting back to me quickly.
