### ISSUE TITLE
The hosting bundles aren't listed

### ISSUE THREAD

**Issue by dushkostanoeski** [dotnet/cli-lab#140]
As you can see , the hosting bundles are installed, but not listed when using the uninstall tool.

![image](https://user-images.githubusercontent.com/1545030/78684861-44815700-78f1-11ea-8aba-4a4013688e66.png)

**Comment by RomBrz** [comment]
Same here. I tried installing the dotnet-core-uninstall on a fresh server, then installer manually some dotnet core installers to test, and the Hosting Bundles aren't listed.
