### ISSUE TITLE
Ubuntu 18.04 support? Syntax error: word unexpected (expecting ")"

### ISSUE THREAD

**Issue by nodesocket** [dotnet/cli-lab#143]
Does this tool work on Ubuntu? Getting the following errror:

```
./dotnet-core-uninstall: 3: ./dotnet-core-uninstall: Syntax error: word unexpected (expecting ")")
dotnet-core-uninstall
```

**Comment by sfoslund** [comment]
No, we currently don't support linux. Please see [our docs](https://aka.ms/dotnet-core-uninstall-docs) for more information.
