### ISSUE TITLE
[Cannot uninstall version 5.0.0 and above] 

### ISSUE THREAD

**Issue by sebolio** [dotnet/cli-lab#155]
i need to uninstall 5.0 sdk/runtime on macOS catalina, how am I supposed to do it when the official tool doesn't support it ?

**Comment by sfoslund** [comment]
For now we've made the decision to make this tool applicable only to .NET Core SDKs/runtimes, so we do not support uninstalling .NET 5+. You can try using the [dotnet-uninstall-pkgs script](https://github.com/dotnet/cli/blob/master/scripts/obtain/uninstall/dotnet-uninstall-pkgs.sh) as an alternative. 

cc @KathleenDollard
