### ISSUE TITLE
Typo in list command output 

### ISSUE THREAD

**Issue by jstallm** [dotnet/cli-lab#161]
Typo in list output , should be "are" not "areÿ"

see below of output demo with bug

dotnet-core-uninstall.exe list

This tool can not uninstall versions of the runtime or SDK that **areÿ**

**Comment by sfoslund** [comment]
I'm not able to repro this, it is likely an issue with the shell or langue configuration you're using. How are you running the tool?

**Comment by jstallm** [comment]
Please close. I can't seem to delete
