### ISSUE TITLE
ZSH@macOS 10: Instead of doing anything, dotnet-core-uninstall just prints "Hello world!"

### ISSUE THREAD

**Issue by fdenzer** [dotnet/cli-lab#162]
After
`dotnet tool install -g dotnet-core-uninstall`

both
`dotnet-core-uninstall`
and
`dotnet-core-uninstall -h`

result in Hello World! being printed.

I am using a MacBook w/ zsh. That's why I exported path as follows:
`export PATH="$PATH:/Users/LOCAL_USER_NAME_HERE/.dotnet/tools"`

**Comment by fdenzer** [comment]
"Why isn’t the .NET Core Uninstall Tool a .NET Core Global Tool?" is in the readme. I did not know this, since
https://docs.microsoft.com/de-de/dotnet/core/additional-tools/uninstall-tool?tabs=macos does not state that it cannot work when installed globally.

**Comment by sfoslund** [comment]
We have not published the uninstall tool as a global tool, the only way to install it is through the installers on the releases page of this repo.

@KathleenDollard apparently someone has published a dotnet tool with the same name as this tool, that could get very confusing given how many requests we've had for making this a global tool.

**Comment by sfoslund** [comment]
Closing this issue as it appears to be confusion between a dotnet tool and this uninstall tool.
