### ISSUE TITLE
Uninstall .NET 5 RC2 on MacOS

### ISSUE THREAD

**Issue by shanemikel** [dotnet/cli-lab#164]
How do I remove .NET 5 RC2 on MacOS?  The output of `dotnet-core-uninstall list` is:
```
This tool can not uninstall versions of the runtime or SDK that are installed using zip/scripts. The versions that can be uninstalled with this tool are:

.NET Core SDKs:
  5.0.100-rc.2.20479.15  (x64)  [Cannot uninstall version 5.0.0 and above]

.NET Core Runtimes:
  5.0.0-rc.2.20475.17  (x64)  [Used by Visual Studio for Mac or SDKs. Specify individually or use —-force to remove]
```

And the result of `sudo dotnet-core-uninstall remove --sdk 5.0.100-rc.2.20479.15` is the following error:
```
Uninstallation not allowed. This tool cannot uninstall .NET Core SDKs with version 5.0.0 or above.
```

**Comment by sfoslund** [comment]
Right now we do not support uninstalling .NET 5+ with this tool. You can try using the [dotnet-uninstall-pkgs script](https://github.com/dotnet/cli/blob/master/scripts/obtain/uninstall/dotnet-uninstall-pkgs.sh) as an alternative. (cc @marcpopMSFT)
