### ISSUE TITLE
Uninstallation not allowed. This tool cannot uninstall .NET Core SDKs with version 5.0.0 or above

### ISSUE THREAD

**Issue by schipplock** [dotnet/cli-lab#165]
Dear dotnet Team,
I just installed dotnet core 5 on macOS 11.0.1 (the the intel x64 version) and realized that debugging doesn't work (probably a rosetta 2 thing, sadly there is no M1 build yet).

I now want to uninstall dotnet core 5 because it's of no use for me at the moment.

**But all I get is:**

`Uninstallation not allowed. This tool cannot uninstall .NET Core SDKs with version 5.0.0 or above`

I would be happy if you update this tool to remove also version 5 of the dotnet core sdk.

Thanks in advance.

Andreas

**Comment by schipplock** [comment]
oh, I only searched in open issues.

I found this: https://github.com/dotnet/cli/blob/master/scripts/obtain/uninstall/dotnet-uninstall-pkgs.sh

And it worked.

Sorry :).

**Comment by panosru** [comment]
@schipplock that tool removed completely all dotnet versions in your system, not quite what `dotnet-core-uninstall` does, so the issue should remain open.

**Comment by felipegouveiae** [comment]
I got the same issue with framework 6 preview 2. This solved my problem. Thanks!
