### ISSUE TITLE
Uninstallation not allowed. This tool cannot uninstall .NET Core with version 5.0.0 or above

### ISSUE THREAD

**Issue by CreepyGnome** [dotnet/cli-lab#167]
So this issue was closed without actually resolving the issue because the reporter decided to uninstall ALL .NET versions from their system which doesn't resolve the issue that you cannot uninstall .NET 5.0.0 specifically without removing all of them.

https://github.com/dotnet/cli-lab/issues/165

Can we reopen this issue and fix or use this issue to fix it with as it is a horrible experience for someone on a Mac as it is already a pain in the arse to get this script installed and runnable due to the latest Mac OS security crap then to go through all that to get the error stating you cannot do what you went through all that to do.

The latest official uninstall tool following these instructions below trigger this issue on MacOS 10.15.7.

https://docs.microsoft.com/en-us/dotnet/core/additional-tools/uninstall-tool?tabs=macos

**Comment by sfoslund** [comment]
This tool is only intended for use with .NET Core installations, so right now we don't support .NET 5+. 
@KathleenDollard to comment on if we would consider expanding support with future releases.

**Comment by CreepyGnome** [comment]
Okay but this shows up via the dotnet CLI and is on a non-Windows computer so is technically .NET Core and so it should be able to remove it. I mean the nuclear option that removes all .NET Core from the Mac works to remove everything and then you have to install each of the ones you wanted to keep back.  Which is a hassle. However, it proves that it is possible for a script to do this so its a matter of updating it.

In short, you really should not release a new version of a product and not provide a safe way to remove just the one you installed.  If someone had and needed a lot of versions, and the .NET 5 was conflicting (as in my situation) you are screwing that user over and they have to remove all and start over again and install all the various versions they require back on as some times you need more than just the latest LTS versions you need some older versions of those and some non-LTS versions for various testing and product support.

**Comment by Taronyu** [comment]
I also stumbled upon this. Space on my Macbook is an issue since it's not upgradeable so I would really prefer to remove old framework version safely.

**Comment by sfoslund** [comment]
Fixed by https://github.com/dotnet/cli-lab/pull/170, we will release a new version with this change soon.
