### ISSUE TITLE
dotnet-core-uninstall unable to list `Hosting Bundle` 5.0.x

### ISSUE THREAD

**Issue by yyjdelete** [dotnet/cli-lab#186]
1. After install ASP.NET Core Runtime 5.0.x(Hosting Bundle for windows), it's not listed in `.NET Core Runtime & Hosting Bundles:` sector. The same thing works well for 3.1.x;

**Comment by sfoslund** [comment]
@yyjdelete are you still seeing this issue? If so, can you provide the following information:

1. Your OS
2. The version of the uninstall tool you're using
3. The full version of the hosting bundle that's failing to show up

Thanks!

**Comment by yyjdelete** [comment]
Yes, it still not work for latest version

Your OS: win10-x64(21H1, 19043.1110)
The version of the uninstall tool you're using: 1.2.206301
The full version of the hosting bundle that's failing to show up: 5.0.9
https://download.visualstudio.microsoft.com/download/pr/a0f49856-eec9-4962-8d81-b09af6be9435/1d5fc0083b7f7e10ebed181329ca88ae/dotnet-hosting-5.0.9-win.exe

**Comment by yyjdelete** [comment]
@sfoslund 
Yes, it still not work for latest version

Your OS: win10-x64(21H1, 19043.1110)
The version of the uninstall tool you're using: 1.2.206301
The full version of the hosting bundle that's failing to show up: 5.0.9
https://download.visualstudio.microsoft.com/download/pr/a0f49856-eec9-4962-8d81-b09af6be9435/1d5fc0083b7f7e10ebed181329ca88ae/dotnet-hosting-5.0.9-win.exe

**Comment by sfoslund** [comment]
I was able to repro, thanks! This will be fixed in the next release.
