### ISSUE TITLE
Cannot uninstall version 6.0.0 and above

### ISSUE THREAD

**Issue by tillig** [dotnet/cli-lab#189]
Somewhat related to #167 it appears .NET 5 was added to the list of things that can be uninstalled but .NET 6 (admittedly still in preview) is not added yet, at least on Mac OS.

Is this something already in progress or for which a PR would be accepted?

**Comment by tillig** [comment]
For reference, console output from v1.2 of the tool?

```text
 pwsh> sudo ~/dotnet-core-uninstall list

This tool cannot uninstall versions of the runtime or SDK that are installed using zip/scripts. The versions that can be uninstalled with this tool are:

.NET Core SDKs:
  6.0.100-preview.5.21302.13  (x64)  [Cannot uninstall version 6.0.0 and above]
  5.0.301                     (x64)  [Used by Visual Studio for Mac. Specify individually or use —-force to remove]
  3.1.410                     (x64)
  2.1.816                     (x64)
  2.1.811                     (x64)
```

**Comment by sfoslund** [comment]
Hi @tillig, this is by design, we will release a new version of this tool that supports uninstalling .NET 6 around the time that it GAs, see the discussion here: https://github.com/dotnet/cli-lab/issues/160#issuecomment-871506865
