### ISSUE TITLE
dotnet-core-uninstall list does not seem to be aware of any installs

### ISSUE THREAD

**Issue by taori** [dotnet/cli-lab#199]
I stumbled upon this tool through docs - apparently the latest version isn't functional because it does not see any installs at all?

![grafik](https://user-images.githubusercontent.com/5545184/132711018-9d1bb817-fb0f-400a-ba26-ba28239cfe8e.png)

**Comment by sfoslund** [comment]
@taori how did you install these runtimes? Were they standalone runtimes or did they come with the sdk? Installed via visual studio, zips, or standalone msis?

**Comment by taori** [comment]
7.0.0 was installed through powershell, the rest is installed through VS i am pretty sure

**Comment by sfoslund** [comment]
Ah, that would be why. The uninstall tool only supports uninstalling .NET bundles that were installed using standalone installers. Zip installations (including powershell) would have to be removed manually and VS installations can be managed through the VS installer. I'm going to go ahead and close this, but let me know if you have any further questions, thanks!

**Comment by taori** [comment]
@sfoslund Yeah. Thanks for clarifying
