### ISSUE TITLE
Plans for 7.0.0?

### ISSUE THREAD

**Issue by J-Swift** [dotnet/cli-lab#230]
Hi! I notice you explicitly prevent removal of 7.0.0 here https://github.com/dotnet/cli-lab/blob/ec93eb01276fd3692f18912dbe204f0b719f9cad/src/dotnet-core-uninstall/Shared/VSVersioning/VisualStudioSafeVersionsExtractor.cs#L16. Any plans to add that?

**Comment by xbIm** [comment]
what are other options to delete 7.0 preview?

**Comment by baronfel** [comment]
Hi folks - we'll need to bump that version and make a new release in order for the tool to work on 7.0 releases. We're looking at this now!
