### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by savaio** [dotnet/cli-lab#245]
Hello, i want to ask how active is this project? Because there is .NET 7 and 1 year without any release of this app.

**Comment by robertok77** [comment]
> Hello, i want to ask how active is this project? Because there is .NET 7 and 1 year without any release of this app.

It looks like there is nobody in the company, Microsoft fired 1,800 employees this July ...

**Comment by LindaLawton** [comment]
Same issue

**Comment by nagilson** [comment]
There's a PR out to allow uninstall of .NET 7 that's been in the works for a bit: https://github.com/dotnet/cli-lab/pull/235

FWIW: don't take this as an official answer. @marcpopMSFT  could answer better. But from my not-Microsoft-endorsed-but-Microsoft-employee-perspective, _Theoretically_ this is still in support but I don't really think there's official capacity for it ATM.

**Comment by marcpopMSFT** [comment]
The answer is best effort. This project doesn't have an official owner at the moment inside the company. Our plan had been to update it once a year for the new version but infrastructure atrophy plus compliance costs means this is going to be a larger cost than expected. At a minimum, we'll work on getting the 7.0 support PR in and prioritize ensuring the 8.0 support gets in on time next year.  Beyond that, we're not investing here.

**Comment by baronfel** [comment]
We've just released [1.6.0](https://github.com/dotnet/cli-lab/releases/tag/1.6.0) with the required updates for managing 7.0 SDKs - please take that for a spin and let us know how it goes!

**Comment by nagilson** [comment]
I nominate @baronfel's dog to be the temporary maintainer of dotnet/uninstaller to give him an n-1 of the Hilbert's Grand Hotel number of things he's undertaking
