### ISSUE TITLE
How to handle a version that VS depends on

### ISSUE THREAD

**Issue by wli3** [dotnet/cli-lab#26]
Like VS 15.9 depends on SDK 2.1.300(? not sure that is the exact version). And it cannot depend on a higher version. Remove it will break VS.

**Comment by yuchong-pan** [comment]
As discussed, we will have a documentation section explaining VS dependencies on .NET Core SDKs. See https://github.com/dotnet/docs/pull/13562/commits/fd7caf9712437e433b3ba686810e7916b36fcc6a.
