### ISSUE TITLE
Why only macOS and Windows??? dotnet.core-uninstall for Linux?

### ISSUE THREAD

**Issue by DeafMan1983** [dotnet/cli-lab#261]
Hello ,

what is the h#ll?

Why do you not care poor penguins :( ?
I expected Microsoft has enough to use WSL3 and dotnet uninstall tool for nothing? I am very disappointed.....

I have downloaded Source of dotnet-core-uninstall for Linux and it building time and gets errors...

Please care for Linux....!

Thanks!

**Comment by baronfel** [comment]
If you're using the system package manager to install runtimes and SDKs, then you do not need the uninstall tool at all - you can uninstall unwanted packages with the appropriate package manager command.

For example, to remove the .NET 6.0 from a Debian/Ubuntu system you'd run 'apt remove dotnet-sdk-6.0'.

**Comment by DeafMan1983** [comment]
Ok but how do I remove if I worked with dotnet-install.sh

**Comment by tareqimbasher** [comment]
I am also looking for a way to uninstall a specific .NET SDK version that was installed with dotnet-install.sh

**Comment by tareqimbasher** [comment]
I am also looking for a way to uninstall a specific .NET SDK version that was installed with dotnet-install.sh

**Comment by baronfel** [comment]
@tareqimbasher SDKs installed with dotnet-install.sh are not visible by this tool, but there's good news - you can remove them just by uninstalling the folder where they were installed to.

**Comment by tareqimbasher** [comment]
Right, but I want to remove just a specific SDK version, not all of them. I'm not exactly sure which directories belong to a specific SDK version and which ones should not be deleted. The possibly naive way to figure it out is say I want to delete .NET 6 SDK, then I remove all directories with the name `6.*` but I'm not sure that is what I really should be doing or if that's everything that needs deleting.

[These](https://wiki.archlinux.org/title/.NET#Uninstall_manually_installed_version) instructions are promising, but I couldn't find any official docs to corroborate.

**Comment by DeafMan1983** [comment]
Oh sorry for my inactivity! I have tried to uninstall but sometimes not working. That's why reinstallation makes me much easier.

Remember that if you are confused about 2 directories of Dotnet under Ubuntu lib and share.

Like you notice where is SDK installation. Don't copy and paste! Just link symbolic directory sdks in `/usr/lib/dotnet` for `/usr/share/dotnet/sdks`
```
sudo ln -s /usr/lib/dotnet/sdk /usr/share/dotnet/sdks
```
And check `dotnet --list-sdks` and it shows up any installed sdks.

Now I would like to close my discussion because I have no problem now.
