### ISSUE TITLE
[NETSDKE2E][MAC] Throw an unhandled exception in dotnet-core-uninstall list output.

### ISSUE THREAD

**Issue by v-xiaofchen** [dotnet/cli-lab#287]
### To Reproduce
1.install dotnet-core-uninstall(1.7.0) from https://dnceng.visualstudio.com/_apis/resources/Containers/16714346/drop-osx?itemPath=drop-osx%2Fdotnet-core-uninstall.tar.gz
2. Use the following commands to install the tool:
```
mkdir -p ~/dotnet-core-uninstall
tar -zxf dotnet-core-uninstall.tar.gz -C ~/dotnet-core-uninstall
cd ~/dotnet-core-uninstall
./dotnet-core-uninstall list
```
3.Install SDK 8.0.201from https://dotnet.microsoft.com/en-us/download/dotnet/8.0
4. Run "./dotnet-core-uninstall list"
5.check the output of dotnet-core-uninstall list

### Expected Result:
The version(s) of the .NET 8 SDK you installed appear in the output.
### Actual Result:
Throw an unhandled exception in dotnet-core-uninstall list output.
![image](https://github.com/dotnet/cli-lab/assets/99376012/c55045af-eb3b-496d-98c0-fc5f305a25d5)

### dotnet --info:
![image](https://github.com/dotnet/cli-lab/assets/99376012/b4389e0a-f70a-4376-af65-b88c3579eca0)

### Note:
This issue also repro on.NET 6/7.

**Comment by baronfel** [comment]
Here's the line in question: 

https://github.com/dotnet/cli-lab/blob/main/src/dotnet-core-uninstall/Shared/Configs/CommandLineConfigs.cs#L244C79-L244C97

This looks like an incorrect use of System.CommandLine to me - we're getting `Environment.GetCommandLineArgs()` in the static constructor of a type - this should only happen sometime after `Main(stirng[] argv)`.
