### ISSUE TITLE
[NETSDKE2E] After uninstalling 8.0.2 Hosting-Bundle, the x86 ".NET Runtime" and "ASP.NET Runtime" are still in dotnet-core-uninstall list output.

### ISSUE THREAD

**Issue by v-ainigao** [dotnet/cli-lab#288]
1.install dotnet-core-uninstall(1.7.515801)
2.install 8.0.2 Hosting-Bundle
3.Run `dotnet-core-uninstall list`
4.Check the output of `dotnet-core-uninstall list`
5.Run `dotnet-core-uninstall remove --hosting-bundle --all`
6.Check the output of `dotnet-core-uninstall list`

Expected Result:
The output of dotnet-core-uninstall list will remove all runtimes info.

Actual Result:
The x86 ".NET Runtime" and "ASP.NET Runtime" are still in the `dotnet-core-uninstall list` output, but x64 has been removed.
![image](https://github.com/dotnet/cli-lab/assets/106054229/315d03a3-d145-45d5-bf17-ea4e9e26ed85)
![image](https://github.com/dotnet/cli-lab/assets/106054229/e3e89194-16e3-4234-997d-ebce0325a381)

**Comment by vdanche** [comment]
not repro on net9 sdk with uninstall tool 1.7.550802
![Image](https://github.com/user-attachments/assets/2081f873-08e2-457c-94c3-d3428d9c0fbb)
![Image](https://github.com/user-attachments/assets/5d78507a-cbcd-4a03-abfb-f38cca9148cf)

**Comment by marcpopMSFT** [comment]
I believe this will be resolved by the latest hosting bundled as we made a change a couple of months ago in 8 to change the default behavior. @vdanche can you confirm?

CC @joeloff
