### ISSUE TITLE
[NETSDKE2E]Specified versions are not displayed after running "--all-lower-patches".

### ISSUE THREAD

**Issue by v-ainigao** [dotnet/cli-lab#296]
1.install dotnet-core-uninstall(1.7.521001)
2.install 8.0.100-preview.7.23376.3 SDK(x64) + 8.0.204 SDK(arm64) + 8.0.100-preview.7.23376.3 SDK(x86)
3.Run `dotnet-core-uninstall list`, we can see three SDKs displayed.
![image](https://github.com/dotnet/cli-lab/assets/106054229/420f8973-baa9-4224-84d3-08963a2028dc)
4.Run `dotnet-core-uninstall dry-run --all-lower-patches --sdk --force` to check if all lower patches is displayed.

Expected Result:
We can see all lower patches displayed.

Actual Result:
All lower patches is not displayed.
![image](https://github.com/dotnet/cli-lab/assets/106054229/a847439b-5543-4453-83ec-34f748144242)

**Comment by vdanche** [comment]
we re-check again, we should install 8.0.100 SDK(arm64) instead of 8.0.204 SDK(arm64), so this is not a valid issue. hence close it
![image](https://github.com/dotnet/cli-lab/assets/65637796/0a5c024c-0a58-4e63-bdcb-156eea811b52)
