### ISSUE TITLE
[NETSDKE2E][MAC] The option "-?" doesn’t work.

### ISSUE THREAD

**Issue by v-xiaofchen** [dotnet/cli-lab#298]
**To Reproduce**
1.Prepare a clean MacOS.
2.install dotnet-core-uninstall(1.7.0) from [tar](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdnceng.visualstudio.com%2F_apis%2Fresources%2FContainers%2F17097018%2Fdrop%3FitemPath%3Ddrop%252Fdotnet-core-uninstall.tar.gz&data=05%7C02%7Cv-ainigao%40microsoft.com%7C069b3fabee524813ebcc08dc5cea5096%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638487408662461161%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=xUbJQZsisuqNG85%2BAF%2BNr42cMvu%2FPmYjGYBY%2FBfgLg4%3D&reserved=0)
3. Use the following commands to install the tool:

```
mkdir -p ~/dotnet-core-uninstall
tar -zxvf dotnet-core-uninstall.tar.gz -C ~/dotnet-core-uninstall
cd ~/dotnet-core-uninstall
./dotnet-core-uninstall list
```
4.Install 8.0.204(osx-x64) from https://dotnet.microsoft.com/en-us/download/dotnet/8.0
5. Run "./dotnet-core-uninstall -h"
6.Run "./dotnet-core-uninstall -?' and observer

**Expected Result:**
The option "-?" can work.

**Actual Result:**
The option "-?" doesn’t work.
![image](https://github.com/dotnet/cli-lab/assets/99376012/7c832786-af5d-480b-8c85-406a49c8c358)

**Comment by vdanche** [comment]
not repro on win11-x64
![image](https://github.com/dotnet/cli-lab/assets/65637796/ddc1faa8-c348-4fd5-9cc5-e9813a4fac7b)

**Comment by baronfel** [comment]
This is a problem with the `zsh` shell used by the tester - `zsh` will attempt to expand the `?` character as a wildcard so it doesn't find any matching commands. You can fix this by telling zsh to not glob via `unsetopt nomatch`. There are more details at https://github.com/ohmyzsh/ohmyzsh/issues/31.
