### ISSUE TITLE
CommandNotFoundException

### ISSUE THREAD

**Issue by LostBeard** [dotnet/cli-lab#309]
OS:
Windows 10 64bit

Installer used: 
dotnet-core-uninstall-1.7.521001.msi

I followed the straightforward instructions on the [Releases](https://github.com/dotnet/cli-lab/releases) page. I got to step 5: `Run the tool by using dotnet-core-uninstall.`. I opened a new elevated PowerShell window and ran `.\dotnet-core-uninstall` and got the error shown below. I even tried running the command in its own install folder.

```
PS C:\Program Files (x86)\dotnet-core-uninstall> .\dotnet-core-uninstall
.\dotnet-core-uninstall : The term '.\dotnet-core-uninstall' is not recognized as the name of a cmdlet, function,
script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is
correct and try again.
At line:1 char:1
+ .\dotnet-core-uninstall
+ ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (.\dotnet-core-uninstall:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

I also tried running `dotnet-core-uninstall` in an elevated Command Prompt and got a similar error.
```
'dotnet-core-uninstall' is not recognized as an internal or external command,
operable program or batch file.
```

I noticed there is no .exe in the install folder named `dotnet-core-uninstall.exe`. The only exe in that folder is `createdump.exe` (190 files total.) The file `dotnet-core-uninstall.pdb` is there though.

I might be missing something simple. Thanks for the help.

**Comment by baronfel** [comment]
My guess is that you downloaded the macos binary instead of the windows exe. Can you check your download and the releases page again and see if that's the case?

**Comment by LostBeard** [comment]
Really? if `dotnet-core-uninstall-1.7.521001.msi` is the MacOS installer and it magically runs on Windows 10 and installs everything except the needed exe.... That would be interesting.

**Comment by LostBeard** [comment]
I'll wait for someone who can read and comprehend. But thanks for the effort.

**Comment by baronfel** [comment]
Apologies - I was responding from my phone. I've now gone to my desk and verified everything you wrote in your initial response. It seems that the windows build is in fact not bundling the application. In fact, I would have expected the MSI to have a single-file install similar to the contents of the macOS tarball. That's not the case, and it points to something that's regressed in our work to get this repo compliant with required DevDiv processes.

**Comment by LostBeard** [comment]
Thank you. I will try a lower release version or wait until a new version is released.

**Comment by baronfel** [comment]
I've built a local version of the tool and confirmed that a) the project publish creates the exe (as expected) and b) the built MSI also contains the exe (also as expected).  What's confusing the heck out of me is that we had internal testing/validation done with these bits and had no errors reported from our testing team - and this would have failed immediately as you found.

**Comment by joeloff** [comment]
The EXE is part of the MSI

![Image](https://github.com/user-attachments/assets/f09cae2f-bcf0-42fa-9af1-de7c595c53fb)

Let me dig around some more

**Comment by joeloff** [comment]
Latest release installs fine

![Image](https://github.com/user-attachments/assets/fe30abd8-992c-4bd3-a780-1b697f641045)

@LostBeard can you share the MSI log? I'm guessing you just ran the MSI directly, so it will likely be under your %temp% directory in a file similar to `MSI5b82e.LOG`.  Probably can do something like `findstr /snip dotnet-core-uninstall %TEMP%\MSI*.log` to find it, though `findstr` sometimes struggle with encoded files.

Have you tried running a repair?

**Comment by joeloff** [comment]
I've confirmed, it's a problem with the upgrade. @LostBeard for now, just repair the MSI

**Comment by baronfel** [comment]
@LostBeard thanks for raising this - I've added wording to both the current release and the 1.6.0 release warning users about the faulty build and the prereq to remove the 1.6.0 release before installing new releases.

**Comment by LostBeard** [comment]
I uninstalled and re-installed and it fixed it. There is now 205 items in the install folder including the `dotnet-core-uninstall.exe` file that wasn't there before. I think the original install had failed but didn't give any indication of the failure.

**Comment by LostBeard** [comment]
> [@LostBeard](https://github.com/LostBeard) can you share the MSI log? I'm guessing you just ran the MSI directly, so it will likely be under your %temp% directory in a file similar to `MSI5b82e.LOG`. Probably can do something like `findstr /snip dotnet-core-uninstall %TEMP%\MSI*.log` to find it, though `findstr` sometimes struggle with encoded files.

My `%temp%` folder is `C:\Users\Lost\AppData\Local\Temp` (just an fyi in case you have another folder I might check.)

I can't find the log file. The findstr command seemed to just hang. I used VS Code to search the %temp% folder and only 4 files contained the `dotnet-core-uninstall` string and they were just logs from other installers that were writing out the current `Path` environment variable value (`C:\Program Files (x86)\dotnet-core-uninstall\`.) 

> Have you tried running a repair?

I did not. I uninstalled and re-installed, which worked. A repair would likely have worked also. 👍

**Comment by LostBeard** [comment]
Version 1.7 is the only version I have ever installed and it failed the first time but worked the second. Maybe a registry entry read/write fails the first time but works the 2nd time? 

I used `dotnet-core-uninstall-1.7.521001.msi` both times.

**Comment by joeloff** [comment]
MSI logging might be turned off. There's a policy key you can query from a command prompt using `reg query HKLM\SOFTWARE\POLICIES\Microsoft\Windows\Installer /s`

You should see something like

```
HKEY_LOCAL_MACHINE\SOFTWARE\POLICIES\Microsoft\Windows\Installer
    Logging    REG_SZ    oicewarmupv
```

If not, you can create the key and it will enable automatic logging.
