### ISSUE TITLE
Setup aka.ms/dotnet-core-uninstall

### ISSUE THREAD

**Issue by yuchong-pan** [dotnet/cli-lab#41]
As discussed in an offline meeting with @KathleenDollard and @rowanmiller, the name of the tool will be `dotnet-core-uninstall` and the aka.ms link will be "aka.ms/dotnet-core-uninstall".

We probably also want to remove the link "aka.ms/dotnet-cleanup", which we setup before.

Question for @KathleenDollard: Should "aka.ms/dotnet-core-uninstall" point to [the tool download page](https://dotnet.microsoft.com/download/dotnet-core/uninstall-tool) or to [How to remove the .NET Core Runtime and SDK](https://docs.microsoft.com/en-us/dotnet/core/versions/remove-runtime-sdk-versions?tabs=windows)?

The help page has been changed accordingly. See Pull Request #40.

**Comment by KathleenDollard** [comment]
@rowanmiller Any thoughts on this?

My vote is the docs page. Among other things, we can set it up now and change it later if we think that's the right thing to do.

**Comment by rowanmiller** [comment]
I don't have a strong opinion. If you are using the link to announce the tool, then it might make more sense to take them to the dedicated page for downloading the tool. If it's going to be used more generally for uninstalling, then the docs page makes more sense.

**Comment by wli3** [comment]
@yuchong-pan this is done?

**Comment by yuchong-pan** [comment]
@wli3 Yes, this is done. It currently points to https://docs.microsoft.com/en-us/dotnet/core/versions/remove-runtime-sdk-versions. However, following the suggestions from the docs team, we will create a separate documentation page for the tool, so we may want to point the link to that page instead later.

**Comment by yuchong-pan** [comment]
Closing this issue since it's done.
