### ISSUE TITLE
`sdk` and `runtime` as subcommands

### ISSUE THREAD

**Issue by yuchong-pan** [dotnet/cli-lab#46]
Since we have now switched from a global tool to a self-contained console app, do we consider switching the options `--sdk` and `--runtime` (and potentially others) to subcommands so that they are clearly exclusive?

For instance, instead of `dotnet-core-uninstall 2.2.300 --sdk`, we use `dotnet-core-uninstall sdk 2.2.300`.

**Comment by KathleenDollard** [comment]
I missed this. Is it still relevant?

**Comment by yuchong-pan** [comment]
Hi @KathleenDollard. I think it's not a big issue for the preview versions. I'm just wondering if changing `sdk` and `runtime` to subcommands would improve user experience because that's less confusing as we discussed before.

**Comment by sfoslund** [comment]
Tool command and option syntax has been updated since this issue creation. Closing as out of date.
