### ISSUE TITLE
Need a write of how to install it

### ISSUE THREAD

**Issue by wli3** [dotnet/cli-lab#57]
It is a self-contained app now. If we don't have the installer, we need a doc for how to install it (need to be in _program files_)

**Comment by yuchong-pan** [comment]
Closing this issue because an paragraph of installation instructions has been added in #54.

> ### Installing
> 
> You can download the .NET Core Installation Cleanup Tool from [https://dotnet.microsoft.com/download/dotnet-core/uninstall-tool](https://dotnet.microsoft.com/download/dotnet-core/uninstall-tool) and put the single executable (`dotnet-core-uninstall.exe`) in a directory.
> 
> __Note__: Be aware that, since the tool requires elevation, it should be installed in a write-protected directory (e.g., `C:\Program Files` on Windows).
