### ISSUE TITLE
cannot run build.cmd locally

### ISSUE THREAD

**Issue by wli3** [dotnet/cli-lab#64]
You need to add /p:RuntimeIdentifier=CURRENT_RID to make it build. We should fix it. The minimal we need to do is to document it

**Comment by yuchong-pan** [comment]
I don't think it's worth fixing, as developers can just pass in the `RuntimeIdentifier` parameter using `/p:RuntimeIdentifier=<RID>`, as you mentioned. We should document this in `README.md` as building instructions.
