### ISSUE TITLE
MSBuild binlog query language proposal

### ISSUE THREAD

**Issue by yuchong-pan** [dotnet/cli-lab#77]
1. Messaging
    1. List all messages (same for warnings/errors)
        ```
        /message
        ```
    2. List messages emitted by the specified project (same for warnings/errors)
        ```
        /message[project=Project.csproj]
        ```
    3. List messages emitted by the specified project with the specified target framework (same for warnings/errors)
        ```
        /message[project=Project.csproj, targetFramework=win-x64]
        ```
    4. List messages emitted by the specified project and target (same for warnings/errors)
        ```
        /message[project=Project.csproj, target=TargetName]
        ```
    5. List messages emitted by the specified project, target and task (same for warnings/errors)
        ```
        /message[project=Project.csproj, target=TargetName, task=TaskName]
        ```
2. Projects
    1. List projects that the specified project directly depends on (i.e., should run before the specified project)
        ```
        /project[directlyBeforeProject=Project.csproj]
        ```
    2. List projects that directly depend on the specified project (i.e., the specified project should run before those projects)
        ```
        /project[directlyDependOnProject=Project.csproj]
        ```
    3. List all projects that the specified project depends on, either directly or indirectly (i.e., should run before the specified project)
        ```
        /project[beforeProject=Project.csproj]
        ```
    4. List all projects that depend on the specified project, either directly or indirectly (i.e., the specified project should run before those projects)
        ```
        /project[dependOnProject=Project.csproj]
        ```
3. Targets
    1. List targets that the specified target directly depends on (i.e., should run before the specified target)
        ```
        /target[directlyBeforeTarget=TargetName, project=Project.csproj]
        ```
    2. List targets that run directly after the specified target
        ```
        /target[directlyAfterTarget=TargetName, project=Project.csproj]
        ```
    3. List targets that directly depend on the specified target (i.e., the specified target should run before those targets)
        ```
        /target[directlyDependOnTarget=TargetName, project=Project.csproj]
        ```
    4. List all targets that the specified target depends on, either directly or indirectly (i.e., should run before the specified target)
        ```
        /target[beforeTarget=TargetName, project=Project.csproj]
        ```
    5. List targets that run after the specified target, either directly or indirectly
        ```
        /target[afterTarget=TargetName, project=Project.csproj]
        ```
    6. List all targets that depend on the specified target, either directly or indirectly (i.e., the specified target should run before those targets)
        ```
        /target[dependOnTarget=TargetName, project=Project.csproj]
        ```

**Comment by rainersigwald** [comment]
Questions:

1. Which of these are fully general? Can _any_ node be queried on its context using `Project=` and `Target=`?
1. How would `targetFramework` be implemented? Is it a special case, or is this general and can find any properties?
1. These single-or-multiple-result queries are a good place to start. But how will graph operations like "tasks in targets that were depended upon by project X" be expressed?

**Comment by yuchong-pan** [comment]
Replies to @rainersigwald's questions:
1. For now every node can be queries using `Project=`, but project nodes cannot be queried using `Target=`.
2. For now, if `targetFramework` isn't specified, I'm planning to aggregate all project instance nodes associated with that project file. If it is specified, then I will filter project instance nodes associated with that project file and with the specified target framework in the global properties.
3. Can we use the reversed graph?

**Comment by rainersigwald** [comment]
for 3 I'm more thinking about "what does the expression look like?"

For instance, in XPath you can do things like

```xpath
//ul/li[contains(text(),'doprep')]/following-sibling::li
```

to find siblings of the `li` that matches the filter. What does that look like here?

**Comment by yuchong-pan** [comment]
I'm wondering if we can do
```
/project[beforeProject=ProjectX.csproj]/target/task
```

**Comment by rainersigwald** [comment]
Ok, and what about "all log messages from tasks that had at least one error"?

**Comment by yuchong-pan** [comment]
Things get complicated here. I think we should probably modify queries for messaging to make messages, warnings and errors "children" of projects, targets and tasks. So the queries will become
```
/message
```
```
/project[name=Project.csproj]/message
```
```
/project[name=Project.csproj, targetFramework=win-x64]/target/message
```

I need to investigate into how errors are related to messages. I'm wondering if there is `TaskId` in the build context of the error which points to a message task. If so, can we do
```
/project/task[count("/error")>=1]/message
```

**Comment by yuchong-pan** [comment]
@rainersigwald 
Do you think things like `directlyBeforeTarget` will be useful?

**Comment by yuchong-pan** [comment]
Updates of the proposal after the meeting with @rainersigwald @livarcocc:

1. Regarding `/` and `//` in XPath:
    The XPath language have `/` for direct children and `//` for descendants. However, in our case, the structure is very clear: `Project -> Target -> Task`, and `Message`, `Warning` and `Error` can be children of `Project`, `Target` and `Task`, or even top-level. Therefore, there is no need to distinguish between `/` and `//` in our language.
2. How users specify a project/target/task:
    Internally, we use ID to distinguish projects/targets and tasks. However, users are not aware of those IDs without us providing the IDs to them. Hence, we should allow users to specify projects, targets and tasks using their names, while leaving it open for them to specify those with IDs, as we can expose API to provide them with a list of IDs.
3. We will treat messages, warnings and errors as nodes.
4. We will allow expression in square brackets, such as `Target[/Error[...]]`.

**Comment by yuchong-pan** [comment]
Closing this issue because this proposal is already outdated and #91 has a more up-to-date design.
